OpenRA.Utility.exe	d2k	--import-d2k-map	A1V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A1V2.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A2V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A2V2.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A3V1.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A3V2.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A4V1.MAP	BLOXICE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A5V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A6V1.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A6V2.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A7V1.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A8V1.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A9V1.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	A9V2.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H2V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H2V2.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H3V1.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H3V2.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H4V1.MAP	BLOXWAST.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H5V1.MAP	BLOXICE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H6V1.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H6V2.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H7V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H8V1.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H9V1.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	H9V2.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O1V1.MAP	BLOXICE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O1V2.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O2V1.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O2V2.MAP	BLOXTREE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O3V1.MAP	BLOXICE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O3V2.MAP	BLOXBASE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O4V1.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O6V1.MAP	BLOXBGBS.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O6V2.MAP	BLOXWAST.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O7V1.MAP	BLOXWAST.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O8V1.MAP	BLOXBAT.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O9V1.MAP	BLOXICE.R8
OpenRA.Utility.exe	d2k	--import-d2k-map	O9V2.MAP	BLOXBGBS.R8
pause